version: "3.3"
services:
    db:
        image: postgres:16
        restart: always
        environment:
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: marten_testing
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "5440:5432"
        volumes:
            - my-db:/var/lib/postgresql/data

volumes:
    my-db:
